CREATE SEQUENCE seq_users START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_tickets START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_slas START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_worklogs START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_ticket_history START WITH 1 INCREMENT BY 1;
